Add support for quarantine case
watchdogpolska/feder pull request #1077
Opened 2021-09-20 20:54 UTC by ad-m

Ja proponuje nowy koncept spraw w kwarantannie. To adresuje zgłaszaną przez @AgnieszkaZdanowicz  pilną potrzebę oznaczenia wybranych spraw jako niedostępnych publicznie przez ograniczony okres czasu ze względu na zaburzenia prawne. 

Pozwala to także na zaadresowanie – zgłaszanych przez np. Bartosza Wilka – zagadnienia prywatnych monitoringów.  Rozumiałbym wówczas prywatny monitoring jako taki dla którego opis jest ogólnodostępny, ale sprawy domyślnie nie są opublikowane, ale mogą. To skłania do tego, aby jednak publikować sprawy, a sam opis to nie wydaje mi się nadmierne wyzwaniem organizacyjnym.

Sprawy w kwarantannie to sprawa, którą uprawniona osoba w monitoringu oznaczały, że jest w kwarantannie poprzez jej standardową edycje. Wówczas taka sprawa (a docelowo  także jej listy itd.) nie jest ogólnodostępna do czasu ponownej edycji. 

Następne PR-y wymagają przejrzenia kodu odpowiedzialnego za monitoringi, przesyłki, listy, załączniki i inne elementy wchodzące w skład sprawy, aby wymusić to podejście szerzej. 

Myślę, że sam kod – na tym etapie – jest dość czytelny:

* wprowadzono nowe uprawnienie `view_quarantied_case` do modelu `Monitoring`
* wprowadzono nowe pole `is_quarantied` do modelu `Case`
* wprowadzono nową metodę `for_user` do klasy `CaseQuerySet`, która wykorzystuje pole `is_quarantied` i uprawnienie `view_quarantied_case`
* wykorzystano metodę `for_user` w widokach z modułu `feder.cases.views`

2021-09-21 04:53 UTC, AgnieszkaZdanowicz commented
@ad-m dzięki wielkie za szybkie zajęcie się sprawą! czy dobrze rozumiem, że czekamy jeszcze na zmergowanie?

2021-09-21 10:02 UTC, ad-m commented
Recenzje od Jakuba, recenzje od Ciebie, zmergowanie i powtórzenie procesu
wobec listów, załączników itd.

wt., 21 wrz 2021, 06:53 użytkownik AgnieszkaZdanowicz <
***@***.***> napisał:

> @ad-m <https://github.com/ad-m> dzięki wielkie za szybkie zajęcie się
> sprawą! czy dobrze rozumiem, że czekamy jeszcze na zmergowanie?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/watchdogpolska/feder/pull/1077#issuecomment-923622659>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3TNL2TURZBKSXFHUA553LUDAFUHANCNFSM5EMZSL7Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-21 10:04 UTC, AgnieszkaZdanowicz commented
Tylko ja nie wiem, co mam recenzować - czy te planowane zmiany są gdzieś widoczne?

2021-09-21 10:16 UTC, ad-m commented
Nie, masz obecnie dostęp do powyższego opisu. Jak Jakub zrecenzuje to Jakub
może wdrożyć na środowisko testowe.

wt., 21 wrz 2021, 12:05 użytkownik AgnieszkaZdanowicz <
***@***.***> napisał:

> Tylko ja nie wiem, co mam recenzować - czy te planowane zmiany są gdzieś
> widoczne?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/watchdogpolska/feder/pull/1077#issuecomment-923828269>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3TNL2A7QGNIXSEP32RHFDUDBKFJANCNFSM5EMZSL7Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-21 10:45 UTC, dzejkobi commented
> Nie, masz obecnie dostęp do powyższego opisu. Jak Jakub zrecenzuje to Jakub może wdrożyć na środowisko testowe.

Tak, zrobię to dziś i dam znać.

2021-09-21 16:47 UTC, dzejkobi requested changes
Generally seems legit, but I would change the field name to "is_quarantined".

2021-09-21 16:47 UTC, dzejkobi commented on feder/cases/models.py
> +    is_quarantied = models.BooleanField(
I think it should be "is_quarantined" - https://translate.google.pl/?sl=en&tl=pl&text=quarantined&op=translate

2021-09-21 16:55 UTC, ad-m commented
Name updated. Feel free to merge & deploy to tests if you don't have other comments.

2021-09-21 17:39 UTC, dzejkobi requested changes
Thanks for the update, but there is still 10 occurrences of "quarantied" word in your PR, so I suggest to change them all to be consistent.

2021-09-21 17:44 UTC, ad-m commented
> Thanks for the update, but there is still 10 occurrences of "quarantied" word in your PR, so I suggest to change them all to be consistent.

Thanks for pointing out. I made that changes too quickly. Fixed.

2021-09-21 19:23 UTC, merged

2021-09-22 02:23 UTC, ad-m commented
@dzejkobi czy planujesz i czy możesz wdrożyć ww. zmiany na środowisko testowe dla @AgnieszkaZdanowicz ?

2021-09-22 11:06 UTC, dzejkobi commented
@ad-m Tak, wdrożyłem na Staging, ale niestety jest błąd:
https://sentry.io/organizations/siecobywatelska/issues/2665162130/?project=5696685&query=is%3Aunresolved