Readme and setup updates
watchdogpolska/feder pull request #861
Opened 2020-10-16 21:53 UTC by rwakulszowa

Przy debugowaniu #831 spędziłem trochę czasu nad lokalnym postawieniem aplikacji.

Wprawdzie samego problemu nie rozwiązałem, ale przy okazji zaktualizowałem dokumentację i dodałem parę komend do manage.py.

2020-10-16 23:40 UTC, ad-m commented on README.rst
> +    make wait_web  # inicjalizacja lokalnych zależności; w razie błędu można wywołać kilkukrotnie
Ja bym raczej ustawił dłuższy czas timeoutu, zamiast rekomendował ponawianie.

2020-10-16 23:43 UTC, ad-m commented on feder/main/management/commands/createsuperuserwithpassword.py
> +    help = "Crate a superuser, and allow password to be provided"
```suggestion
    help = "Create a superuser, and allow password to be provided"
```

2020-10-16 23:45 UTC, ad-m commented on feder/main/management/commands/createsuperuserwithpassword.py
> +class Command(createsuperuser.Command):
Proponuje w tym pliku zamieścić informacje, że komenda jest wymagana wyłącznie w Django <3.0, abyśmy przy sprzątaniu rzeczy poniżej wersji 3.0 wiedzieli, że można to bezpiecznie usunąć. Przyjdzie czas, że odetniemy się od wszystkiego poniżej 3.0.

2020-10-16 23:45 UTC, ad-m commented on README.rst
> +Zbudowanie serwisu:
```suggestion
Zbudowanie usługi:
```

2020-10-16 23:46 UTC, ad-m requested changes
Kosmetyczne zmiany.

2020-10-17 07:19 UTC, rwakulszowa commented
@ad-m Przy okazji - zastanawiałem się nad ujednoliceniem samego pliku readme.
W tym momencie ma format .rst, przy czym treść jest mieszanką rst i markdown. Skoro już edytuję ten plik, mogę od razu go posprzątać, ale zastanawiam się czy preferowany format to .md czy .rst.

Z tego co widzę, aplikacja wykorzystuje .rst w dokumentacji. Z drugiej strony, .md wydaje mi się być zdecydowanie najbardziej powszechnym formatem dla plików readme. Wydaje mi się, że użycie .md miałoby tutaj więcej zalet, ale to tylko moja opinia. Jak uważasz?

2020-10-17 12:48 UTC, ad-m commented
GitHub obsługuje `README.rst`, a – dla mnie – cenniejsze jest efektywność pracy. Dla efektywności pracy lepiej mieć mniej formatów niż więcej. Popieram posprzątanie. Rzucało mi się to ostatnio w oczy ostatnio, ale jeszcze nie na tyle, aby to poprawić.

2020-10-17 14:51 UTC, rwakulszowa commented
Ok, przerobione na rst.
Z rozpędu dodałem do istniejącego commitu, zamiast do nowego.

2020-10-17 15:19 UTC, dzejkobi approved these changes
Generalnie nie mam uwag, poza tym, że komenda `create_social_app` będzie niebawem niepotrzebna w związku z #778 i rezygnacją z uwierzytelniania z wykorzystaniem mediów społecznościowych, pozostanie tylko GSuite.

2020-10-17 15:21 UTC, ad-m commented
@dzejkobi , czy zakładasz porzucenie django-allauth?

2020-10-17 15:42 UTC, dzejkobi commented
> @dzejkobi , czy zakładasz porzucenie django-allauth?

Raczej nie, będzie potrzebne do GSuite.

2020-10-22 00:14 UTC, ad-m approved these changes

2020-10-22 00:14 UTC, merged

2020-10-22 00:14 UTC, ad-m commented
Dziękuje za poczynione zmiany.